name: csv_file
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: ^1.8.0
  csv: ^5.0.2
  faker: ^2.1.0
  csvwriter: ^1.2.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
